In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.preprocessing.sequence import pad_sequences#길이 맞춰줌 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
#Onehot이랑 Embedding이랑 비슷하다고 보머ㅕㄴ됨ㄴ다. 


In [3]:
import numpy as np

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
# 문서의 정의
docs = ['glass of orange juice',
       'bottle of mango juice',
       'glass of mango shake',
       'drink bottle of banana shake',
       'I wnat a glass of cold water',
       'The king and the queen',
       'mand and woman']

In [32]:
vocab_size =10000 #그냥 원핫보다 차원의 축소가 이루어지네 #부정확할순 있어도
#오호. . . 

### 문제1: 원핫인코딩 연습해보자

In [52]:
# 원핫인코딩해보자
#############################################
encoded_docs = [one_hot(d,vocab_size)for d in docs]
#for i in docs:
#    encoded_docs.append(tf.keras.preprocessing.text.one_hot(i,n=vocab_size))
#############################################

In [53]:
print(encoded_docs) #one-hot이랑은 좀 다르게 몇번쨰 단어인지를 호출해줌

[[3162, 715, 6429, 83], [6554, 715, 1960, 83], [3162, 715, 1960, 1557], [8250, 6554, 715, 2856, 1557], [8844, 6053, 9255, 3162, 715, 7523, 9912], [1061, 3626, 2090, 1061, 9632], [5789, 2090, 7105]]


# 단어 임베딩 (Word Embeddings)

In [54]:
embedding_length = 5 # 임베딩 길이 (단어 하나를 5개의 유닛으로 표현해보자.)
max_doc_len = 10  # 문장 길이

### 문제2: 패딩을 시도해보자

In [55]:
# 다음의 pad_sequences를 이용해서 10개의 길이가 되도록 패딩 연습해보자. (디폴트인 pre 대신 post를 사용하라) #뒤에 0을 붙이기 // 앞에 붙이기 
# (https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences)
# tf.keras.preprocessing.sequence.pad_sequences(
#     sequences, maxlen=None, dtype='int32', padding='pre',
#     truncating='pre', value=0.0)

In [56]:
#############################################

encoded_docs =tf.keras.preprocessing.sequence.pad_sequences(encoded_docs,maxlen=max_doc_len, dtype='int32', padding='post',truncating='post', value=0.0)


#############################################

In [58]:
print(encoded_docs)  #(None, 10, 1)

[[3162  715 6429   83    0    0    0    0    0    0]
 [6554  715 1960   83    0    0    0    0    0    0]
 [3162  715 1960 1557    0    0    0    0    0    0]
 [8250 6554  715 2856 1557    0    0    0    0    0]
 [8844 6053 9255 3162  715 7523 9912    0    0    0]
 [1061 3626 2090 1061 9632    0    0    0    0    0]
 [5789 2090 7105    0    0    0    0    0    0    0]]


### 문제3: 5개의 유닛으로 만드는 임베딩 모델을 구축해보자.

In [15]:
#힌트: Embedding() 찾아보자 (https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding)
# tf.keras.layers.Embedding(
#     input_dim, output_dim, embeddings_initializer='uniform',
#     embeddings_regularizer=None, activity_regularizer=None,
#     embeddings_constraint=None, mask_zero=False, input_length=None, **kwargs
# )
# 이중 input_dim, output_dim과 input_length를 정의해보자.

In [62]:
#############################################
model = Sequential()
model.add(Embedding(vocab_size,embedding_length,input_length=max_doc_len))
#############################################

model.compile('adam', 'mse')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 10, 5)             50000     
Total params: 50,000
Trainable params: 50,000
Non-trainable params: 0
_________________________________________________________________


### 문제4: encoded_docs를 (배치크기, 문장길이, 임베딩차원)의 모양으로 만들어라.

In [66]:
# 위에서 만든 모델을 이용해 예측하라.
#############################################

output = model.predict(encoded_docs)
print(output.shape)
print(output)

#############################################


(7, 10, 5)
[[[-1.29545219e-02 -3.96715030e-02 -4.45781462e-02  1.32961385e-02
   -3.67980711e-02]
  [-5.97213581e-03 -4.16231155e-03 -2.08291169e-02 -3.95830721e-03
   -3.19543108e-02]
  [-1.91013459e-02 -2.08219886e-02 -3.24424356e-03 -1.75368413e-02
    4.15449999e-02]
  [-4.54113372e-02 -4.06638160e-02  4.24938314e-02 -4.07925248e-02
   -2.98167225e-02]
  [ 5.28671592e-03 -3.61447223e-02 -4.97544296e-02  3.83739509e-02
    2.34580524e-02]
  [ 5.28671592e-03 -3.61447223e-02 -4.97544296e-02  3.83739509e-02
    2.34580524e-02]
  [ 5.28671592e-03 -3.61447223e-02 -4.97544296e-02  3.83739509e-02
    2.34580524e-02]
  [ 5.28671592e-03 -3.61447223e-02 -4.97544296e-02  3.83739509e-02
    2.34580524e-02]
  [ 5.28671592e-03 -3.61447223e-02 -4.97544296e-02  3.83739509e-02
    2.34580524e-02]
  [ 5.28671592e-03 -3.61447223e-02 -4.97544296e-02  3.83739509e-02
    2.34580524e-02]]

 [[-4.75214832e-02 -4.73344326e-02 -1.82829387e-02 -2.05719471e-02
    4.05713357e-02]
  [-5.97213581e-03 -4.16231155

### 문제5: LSTM 모델을 구축해보라. 

In [68]:
# 은닉상태의 차원은 64로 지정하라.
#############################################

model = Sequential()
model.add(Embedding(vocab_size,embedding_length,input_length=max_doc_len))
model.add(tf.keras.layers.LSTM(64))

#############################################

model.compile('adam', 'mse')
model.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 10, 5)             50000     
_________________________________________________________________
lstm_1 (LSTM)                (None, 64)                17920     
Total params: 67,920
Trainable params: 67,920
Non-trainable params: 0
_________________________________________________________________


### 문제6: 문제5의 LSTM 모델의 출력을 확인하라.

In [69]:
# LSTM의 출력을 산출하고 이의 차원을 확인하라.
#############################################

output = model.predict(encoded_docs)
print(output.shape)
print(output)

#############################################


(7, 64)
[[ 2.5274209e-03  8.2745226e-03  4.2401878e-03  4.9303346e-03
  -4.2099840e-05  1.0598646e-03  7.7816686e-03 -6.6250577e-03
  -8.4357907e-04  5.5254303e-04 -3.4562561e-03 -2.6772174e-03
   7.4570873e-03 -4.6550804e-03 -9.1052512e-03 -9.0879377e-04
  -5.4034935e-03  3.5415376e-03  3.6799272e-03 -8.6506922e-03
   6.4547214e-04  1.0029323e-02  3.7860810e-03 -1.4601554e-03
   2.8862099e-03 -5.4190429e-03 -1.0361163e-03  2.2036012e-03
  -8.2106888e-03  4.8404997e-03  2.8455546e-03  2.6422802e-03
  -2.2483855e-03 -2.1082109e-03 -2.7221581e-04  4.2359596e-03
   2.1550644e-03  1.5763722e-04  1.5717484e-03 -6.9985073e-03
  -5.9911017e-03  5.6834049e-03  4.0696524e-03  4.3884367e-03
   3.3449102e-03 -2.5118385e-03 -2.9393986e-03 -3.3148003e-03
   2.5459309e-03 -7.1418383e-03 -3.9760587e-03 -2.3376117e-03
   6.4607398e-03  1.2557933e-03 -1.0497827e-03  4.0708642e-04
   2.7776659e-03 -4.9132039e-03  6.4625965e-05 -2.2348773e-03
  -6.2799448e-04  2.8910974e-04 -4.9905558e-03  4.5544328e-03]

### 문제7: 감성분석을 할 수 있도록 LSTM을 이용한 로지스틱 모델 예측 모델을 만들어라.

In [24]:
# 힌트: 임베딩 -> LSTM -> Dense, 출력의 갯수가 하나이므로 활성함수를 sigmoid로 사용하라.

In [72]:
#############################################


model = Sequential()
model.add(Embedding(vocab_size,embedding_length,input_length=max_doc_len))
model.add(tf.keras.layers.LSTM(64))
model.add(tf.keras.layers.Dense(1,activation='sigmoid'))
#############################################

model.compile('adam', 'binary_cross_entropy') #결과가 하나니까 바이너리이다.
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 10, 5)             50000     
_________________________________________________________________
lstm_3 (LSTM)                (None, 64)                17920     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 65        
Total params: 67,985
Trainable params: 67,985
Non-trainable params: 0
_________________________________________________________________


### 문제8: 문제 7의 확장된 LSTM 모델의 출력을 확인하라

In [21]:
# 확장된 LSTM의 출력을 산출하고 이의 차원을 확인하라.

In [73]:
#############################################


output = model.predict(encoded_docs)
#############################################

In [74]:
output

array([[0.5030578 ],
       [0.5024724 ],
       [0.50325793],
       [0.50340486],
       [0.5022193 ],
       [0.5033026 ],
       [0.5033202 ]], dtype=float32)

In [75]:
output.shape

(7, 1)